language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
before_install:
  - rvm install 2.5.3
  - gem install bundler
install:
  - npm run install-deps
script:
  - npm run eslint
  - npm run scsslint
  - npm test
  - npm run build
